trigger:
  branches:
    include:
    - '*'
    exclude:
    - '*no-ci*'
  tags:
    include:
    - '*'

pr:
  branches:
    include:
    - '*'
    exclude:
    - '*no-ci*'

stages:
- stage: Testing
  jobs:
    - template: ./.azure-pipelines/azure-pipelines-linux.yml
    - template: ./.azure-pipelines/azure-pipelines-osx.yml
    - template: ./.azure-pipelines/azure-pipelines-win.yml

- stage: Deploy
  condition: and(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/tags/'))
  jobs:
    - job:
      displayName: Deploy Docs and source
      pool:
        vmImage: ubuntu-latest
      variables:
        DISPLAY: ':99.0'
        PYVISTA_OFF_SCREEN: 'True'
      steps:
        - script: echo '##vso[task.prependpath]$CONDA/bin'
          displayName: Add conda to PATH
        - script: |
            conda create --yes --quiet --name test python=$(python.version)
            eval "$(conda shell.bash hook)"
            conda activate test
            conda env list
            conda install --yes --quiet -c conda-forge numpy scipy matplotlib cython vtk properties vectormath pyvista
            pip install -r requirements_dev.txt
            pip install doctr
            pip install .
          displayName: building and installing deps
        - script: |
            eval "$(conda shell.bash hook)"
            conda activate test
            .ci/setup_headless_display.sh
            cd docs
            make html
            cd ..
#            doctr deploy --built-docs ./docs/_build/html/ --deploy-repo simpeg/discretize-docs ./en/master/
          displayName: building documentation
        - script: |
            export TWINE_USERNAME=$(twine.username)
            export TWINE_PASSWORD=$(twine.password)
            eval "$(conda shell.bash hook)"
            conda activate test
            python setup.py sdist
            twine upload --skip-existing dist/*
          displayName: Deploy source
    - job:
      displayName: Windows Wheels
      strategy:
        matrix:
          win-Python36:
            python.version: '3.6'
          win-Python37:
            python.version: '3.7'
          win-Python38:
            python.version: '3.8'
      pool:
        vmImage: vs2017-win2016
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '$(python.version)'
        - script: pip install numpy cython twine wheel
          displayName: Install build dependencies
        - script: python setup.py bdist_wheel
          displayName: Build Wheel
        - script: |
            set TWINE_USERNAME=$(twine.username)
            set TWINE_PASSWORD=$(twine.password)
            call activate build
            twine upload --skip-existing dist/*
          displayName: Upload to PYPI
