trigger:
  branches:
    include:
    - '*'


stages:
- stage: Testing
  jobs:
    -template: ./.azure-pipelines-linux.yml
    -template: ./.azure-pipelines-osx.yml
    -template: ./.azure-pipelines-win.yml
