trigger:
  branches:
    include:
    - '*'


stages:
- stage: Testing
  jobs:
  - job:
    displayName: Running Tests
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
        Python38:
          python.version: '3.8'
    steps:

    - script: echo "##vso[task.prependpath]$CONDA/bin"
      displayName: Add conda to PATH

    - script: conda create --yes --quiet --name test
      displayName: Create Anaconda environment

    - script: |
        source activate test
        conda install --yes --quiet --name test python=${{ python.version }} numpy scipy matplotlib cython vtk
        conda install --yes -c conda-forge properties vectormath pyvista
        pip install -r requirements_dev.txt
        pip install .
      displayName: Install requirements and build

    - script: |
        source activate test
        export KMP_WARNINGS=0
        nosetests -s -v tests/base
      displayName: 'Testing Base'

    - script: |
        source activate test
        export KMP_WARNINGS=0
        nosetests -s -v tests/cyl
      displayName: 'Testing Cylinder Mesh'

    - script: |
        source activate test
        export KMP_WARNINGS=0
        nosetests -s -v tests/tree
      displayName: 'Testing TreeMesh'

    - script: |
        source activate test
        export KMP_WARNINGS=0
        nosetests -s -v tests/docs
      displayName: 'Testing examples, tutorials, and doc build'
