jobs:
- job:
  displayName: Windows
  pool:
    vmImage: windows-latest
  strategy:
    matrix:
      win-Python37:
        python.version: '3.7'
      win-Python38:
        python.version: '3.8'
      win-Python39:
        python.version: '3.9'
  steps:

  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - powershell: |
      call activate base
      conda install --yes -c conda-forge mamba
      mamba create --yes --name test python=$(python.version)
    displayName: Install mamba

  - powershell: |
      call activate test
      mamba install --yes --quiet -c conda-forge numpy scipy matplotlib cython vtk pyvista pymatsolver pytest
    displayName: Create Anaconda environment

  - powershell: |
      call activate test
      pip install -r requirements_dev.txt
      pip install pytest-azurepipelines
    displayName: Install other requirements

  - powershell: |
      call activate test
      pip install -e .
    displayName: Build

  - powershell: |
      call activate test
      pytest -v -s --ignore=tests/docs -W ignore::DeprecationWarning
    displayName: 'Running tests'
