jobs:
- job:
  displayName: Testing on Ubuntu
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      linux-Python36:
        python.version: '3.6'
      linux-Python37:
        python.version: '3.7'
      linux-Python38:
        python.version: '3.8'
  steps:

  - script: echo '##vso[task.prependpath]$CONDA/bin'
    displayName: Add conda to PATH

  - script: |
      conda create --yes --quiet --name test python=$(python.version)
    displayName: Create Anaconda environment

  - script: |
      eval "$(conda shell.bash hook)"
      conda activate test
      conda install --yes --quiet -c conda-forge numpy scipy matplotlib cython vtk properties vectormath pyvista
      pip install -r requirements_dev.txt
      pip install .
    displayName: Install requirements and build

  - script: |
      eval "$(conda shell.bash hook)"
      conda activate test
      pytest tests/base --cov-config .coveragerc --cov=discretize -v -s
    displayName: 'Testing Base'

  - script: |
      eval "$(conda shell.bash hook)"
      conda activate test
      pytest tests/cyl --cov-config .coveragerc --cov=discretize -v -s
    displayName: 'Testing Cylinder Mesh'

  - script: |
      eval "$(conda shell.bash hook)"
      conda activate test
      pytest tests/tree --cov-config .coveragerc --cov=discretize -v -s
    displayName: 'Testing TreeMesh'

  - script: |
      eval "$(conda shell.bash hook)"
      conda activate test
      ./.ci/setup_headless_display.sh
      pytest tests/docs --cov-config .coveragerc --cov=discretize -v -s
    displayName: 'Testing examples, tutorials, and doc build'

  - script: |
      eval "$(conda shell.bash hook)"
      conda activate test
      codecov
