jobs:
- job:
  displayName: Windows
  pool:
    vmImage: windows-latest
  strategy:
    matrix:
      win-Python37:
        python.version: '3.7'
      win-Python38:
        python.version: '3.8'
      win-Python39:
        python.version: '3.9'
  steps:

  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - powershell: |
      Invoke-Webrequest -URI https://micro.mamba.pm/api/micromamba/win-64/latest -OutFile ~\micromamba.tar.bz2
      $env:Path = "C:\PROGRA~1\Git\usr\bin;" + $env:Path
      tar.exe -xvjf ~/micromamba.tar.bz2 --strip-components 2 -C ~ Library/bin/micromamba.exe
      echo "MAMBA_ROOT_PREFIX=~\micromamba" >> $GITHUB_ENV
    displayName: install micromamba

  - powershell: |
      ~\micromamba.exe shell hook -s powershell | Out-String | Invoke-Expression
      micromamba create --yes --quiet -c conda-forge --name test python=$(python.version) numpy scipy matplotlib cython vtk pyvista pymatsolver pip
    displayName: Create Anaconda environment

  - script: |
      call activate test
      pip install -r requirements_dev.txt
      pip install pytest-azurepipelines
    displayName: Install other requirements

  - script: |
      call activate test
      pip install -e .
    displayName: Build

  - script: |
      call activate test
      pytest -v -s --ignore=tests/docs -W ignore::DeprecationWarning
    displayName: 'Running tests'
